### ISSUE TITLE
Post has a cap at 70CHF handling fee

### ISSUE THREAD

**Issue by OneLineTwoBugs** [href/duties#1]
See https://www.post.ch/de/geschaeftsloesungen/export-import-und-verzollung/export/swiss-post-gls/importkosten

Currently, the calculator keeps adding 3% of the value unlimited, but it should be capped at 70 (exkl MWST I think, not sure though)

**Comment by href** [comment]
Sorry for the late reply, did not see this issue until today 😓 

I hope you don't mind I ask you now: Do you have an example where this is wrong? Ideally with a little calculation.

I'm asking, because in principle this should be observed. See the following calculation for Post:

https://github.com/href/duties/blob/78834589c94a7a12867efee06d2810ec1a2f0828/js/math.js#L4-L16

**Comment by OneLineTwoBugs** [comment]
The code looks fine, but the result seems wrong.

![image](https://user-images.githubusercontent.com/17724988/86779373-c5203280-c05b-11ea-926e-bc6c4bc7805d.png)

**Comment by href** [comment]
Thanks for the details, I'll have a look (might take a few days).

**Comment by href** [comment]
I think I found the problem. The 3% was applied twice, once it was capped, once it was not. Hopefully it's correct now. 

If not, feel free to reopen.

Thanks again for reporting this!
